### ISSUE TITLE
sticky header shows overlapping checkbox from body row cell 

### ISSUE THREAD

**Issue by ericpyle** [techniq/mui-table#19]
As you can see in this screenshot, the row text disappears behind the sticky header, but not the checkbox

![image](https://user-images.githubusercontent.com/1125565/44423584-100a2d00-a54c-11e8-85cd-b0cf9b3deb71.png)

**Comment by techniq** [comment]
Add `z-index: 1` to the `th` for the checkbox cell

![image](https://user-images.githubusercontent.com/177476/44438944-79f7f600-a58f-11e8-8b77-2eacb59c06b4.png)
