### ISSUE TITLE
Consider removing lodash.merge

### ISSUE THREAD

**Issue by irrvrsl** [techniq/mui-table#25]
Hello! I've been searching for tiny wrapper around mui table and found your project. It's cool, but I've [checked](https://bundlephobia.com/result?p=mui-table@2.3.2) bundle size of your library and saw that around half of it's size(~10kb minified) is `lodash.merge` package.
Maybe you'll consider to replace it with more lightweight functions, such as:
[merge](https://www.npmjs.com/package/merge)
[deepmerge](https://www.npmjs.com/package/deepmerge)

**Comment by techniq** [comment]
Sounds  reasonable as long as it doesn't break functionality.  Could you send a PR with a replacement?

**Comment by irrvrsl** [comment]
Yes, I can try to replace it, when I'll get home

**Comment by techniq** [comment]
Merged PR #26 and released as [2.4.0](https://github.com/techniq/mui-table/releases/tag/v2.4.0)

**Comment by techniq** [comment]
@irrvrsl Looks to have made a positive impact.  Thanks!

![image](https://user-images.githubusercontent.com/177476/52793901-c4d56080-303c-11e9-8dfb-acb52ee461fa.png)

https://bundlephobia.com/result?p=mui-table@2.4.1
