### ISSUE TITLE
Incorrect PropTypes validation for cellProps

### ISSUE THREAD

**Issue by brianchirls** [techniq/mui-table#9]
See: https://github.com/techniq/mui-table/blob/fef74daf27cab3fe445f9861ab7f2229324140d1/src/index.js#L297
this should be `oneOfType` instead of `oneOf`

**Comment by techniq** [comment]
@brianchirls oops.  fixed in just released `1.1.1`

**Comment by brianchirls** [comment]
That was FAST! 🥇

Thanks.
